In [1]:
import jax.numpy as jnp

In [5]:
x = jnp.arange(0,16).reshape(4,4)
print(x)
x = jnp.expand_dims(x, -1)
x

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]]], dtype=int32)