# 3008ICT Deep Learning (T1 2026)
## Week 1 Lab: Linear Algebra with PyTorch

Welcome to Week 1. This workshop introduces tensor fundamentals in PyTorch.

### Learning Outcomes
By the end of this lab, you should be able to:
- Create tensors from Python lists and NumPy arrays
- Inspect tensor shape, dtype, and device
- Generate tensors with common initialization patterns
- Apply elementwise operations and broadcasting
- Reshape and stack tensors for deep learning workflows

### Before You Start
- Basic Python is assumed.
- Revise vectors, matrices, and elementwise multiplication.
- Run cells in order from top to bottom.

### How To Complete Tasks
- Read each task statement before coding.
- Write your solution in code cells marked `# TODO`.
- Use quick checks such as `.shape`, `.dtype`, and `torch.equal(...)`.

In [1]:
import numpy as np
import torch

### Exercise 1: Creating Tensors

In this exercise, you will create tensors from different data sources and initializations.

#### 1.1 Create a tensor directly from Python data
Task: Create a `2 x 3` tensor from the nested list below.

In [ ]:
data = [[1, 2, 3],[4, 5, 6]]
x_data = torch.tensor(data)

#### 1.2 Create a tensor from a NumPy array
Task: Convert `np_array` into a PyTorch tensor.

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

#### 1.3 Create a tensor of ones with the same shape as `x_np`
Task: Use a helper that preserves shape and dtype.

In [ ]:
x_ones = torch.ones_like(x_np)
x_ones

#### 1.3b Checkpoint Task
Create a tensor of zeros with the same shape as `x_np`.

Hint: Start from `x_np` and reuse its shape instead of hard-coding dimensions.

In [ ]:
x_zeros = torch.zeros_like(x_np)
x_zeros


#### 1.4 Create a tensor with values from a uniform distribution
Task: Create random values in `[0, 1)` with the same shape as `x_data`, cast to float.

In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

#### 1.4b Checkpoint Task
Create a tensor with values from a normal (Gaussian) distribution using the same shape as `x_data`.

Hint: Begin with an existing tensor and generate random values that match its size.

In [ ]:
# TODO: Create a normal-distribution tensor with the same shape as x_data
x_randn = torch.randn_like(x_data)

### Exercise 2: Tensor Attributes

Create a random tensor first, then inspect its key attributes.

#### 2.1 Tensor dimensions (`shape`)

In [2]:
tensor = torch.rand(3,4)
tensor.shape

torch.Size([3, 4])

#### 2.2 Tensor data type (`dtype`)

In [3]:
tensor.dtype

torch.float32

#### 2.3 Tensor device (`cpu` or `cuda`)

In [4]:
tensor.device

device(type='cpu')

### Exercise 3: Create Three Tensors

Create the following tensors:
- `A`: a `4 x 7` matrix of ones
- `B`: a `4 x 7` matrix sampled from a normal distribution
- `C`: a row vector with 7 even numbers from 2 to 14 (inclusive)

Note: This definition of `C` broadcasts cleanly with `A` and `B` in Exercise 4.

In [ ]:
# TODO: Create A, B, and C as specified
A = torch.ones((4,7))
B = torch.randn((4,7))
C = torch.linspace(2, 14, 7).reshape((1, -1))

tensor([[ 2.,  4.,  6.,  8., 10., 12., 14.]])

### Exercise 4: Elementwise Calculation

Using `A`, `B`, and `C` from Exercise 3, compute:

$$
D = A \cdot B + C
$$

where $\cdot$ is elementwise (Hadamard) multiplication.

Checks:
- `D.shape` should be `(4, 7)`
- Do not use matrix multiplication

In [ ]:
# TODO: Compute D = A * B + C
D = A*B + C

torch.Size([4, 7])


### Exercise 5: Column Sums and Scalar Scaling

Given:

$$
A =
\begin{bmatrix}
1 & 2 \\
1 & 1
\end{bmatrix}
$$

$$
B =
\begin{bmatrix}
1 & 2 & 3 \\
3 & 2 & 1
\end{bmatrix}
$$

Tasks:
1. Compute the sum of each column of `A`
2. Compute the sum of all elements in `B` (scalar)
3. Multiply the result from (1) by the scalar from (2) to obtain `C`

Expected check: `C = [24, 36]`

In [15]:
# TODO: Compute C from the column sums of A and total sum of B
A = torch.tensor([[1,2], [1,1]])
B = torch.tensor([[1,2,3], [3,2,1]])

A_col_sums = A.sum(dim=0)

print(A_col_sums)

B_sum = B.sum()
C = A_col_sums * B_sum
C

tensor([2, 3])


tensor([24, 36])

### Exercise 6: Index-and-Value Table from a Matrix

Transform matrix `A` into matrix `B` where:
- the second column of `B` contains flattened values of `A` (row-major order)
- the first column of `B` contains indices from `0` to `n-1`

$$
A =
\begin{bmatrix}
5 & -2 \\
12 & 41
\end{bmatrix}
$$

Target structure:

$$
B =
\begin{bmatrix}
0 & 5 \\
1 & -2 \\
2 & 12 \\
3 & 41
\end{bmatrix}
$$

In [36]:
# TODO: Build B with index and flattened values from A
A = torch.tensor([[5, -2], [12,41]])

B = torch.concat((torch.arange(0, 4).flatten(), A.flatten())).reshape((2,4)).T

B

# A = A.reshape((1,-1))

# print(A)

# B = torch.concat((torch.arange(0, 4).reshape((1, -1)), A), dim=0).T
# B

tensor([[ 0,  5],
        [ 1, -2],
        [ 2, 12],
        [ 3, 41]])

In [37]:
A = torch.tensor([[5, -2], [12,41]])
B = torch.tensor([[8,9], [10, 11]])

print(torch.concat((A, B), dim=0))
print(torch.concat((A, B), dim=1))

tensor([[ 5, -2],
        [12, 41],
        [ 8,  9],
        [10, 11]])
tensor([[ 5, -2,  8,  9],
        [12, 41, 10, 11]])


### Exercise 7: Stack and Slice Three Matrices

Let `A`, `B`, and `C` be matrices of shape `100 x 200`.

Tasks:
1. Stack them into one tensor with a new axis
2. Report the resulting tensor shape
3. Recover matrix `B` by slicing
4. Verify recovery (for example with `torch.equal`)

Hint: Decide which axis should represent "which matrix" before stacking, then slice along that same axis to retrieve `B`.

In [39]:
# TODO: Stack A, B, C and recover B by slicing
A = torch.randn((100, 200))
B = torch.randn_like(A)
C = torch.randn_like(A)

D = torch.stack((A, B, C))

print(D.shape)

B_recov = D[1, :, :]

print(torch.equal(B, B_recov))

torch.Size([3, 100, 200])
True
