# Basics of PyTorch

The material is adapted from d2l.ai

### First, we import torch. Note that although it's called PyTorch, we should import torch instead of pytorch.

In [1]:
import torch
from jax import numpy as jnp

### A tensor represents an array of values, which may have multiple dimensions.

In [2]:
x = torch.arange(12)

xj = jnp.arange(12)

x, xj

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 Array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32))

### The shape of a tensor and the total number of elements in the tensor can be accessed:

In [3]:
x.shape, xj.shape

(torch.Size([12]), (12,))

In [4]:
x.numel(), xj.size

(12, 12)

### To change the shape of a tensor without changing the number of elements or their values, you can call the `reshape` function.

In [5]:
x.reshape(3,4), xj.reshape((3,4))

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 Array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32))

### Create special tensors

In [6]:
torch.zeros(2,3,4), jnp.zeros((2,3,4))

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 Array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32))

In [7]:
torch.ones(2,3,4), jnp.ones((2,3,4))

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 Array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=float32))

### Randomly create tensors using the uniform distribution:

In [8]:
from flax import nnx
import jax

key = jax.random.key(42)

key, norm_key = jax.random.split(key)


torch.rand(3,4), jax.random.uniform(key=norm_key, shape=(3,4), minval=0, maxval=1)

(tensor([[0.0495, 0.7725, 0.1647, 0.6711],
         [0.1660, 0.5292, 0.8442, 0.1357],
         [0.4339, 0.0551, 0.3418, 0.3581]]),
 Array([[0.72766423, 0.78786755, 0.18169427, 0.26263022],
        [0.11072934, 0.20263076, 0.31768847, 0.10557032],
        [0.4298396 , 0.48038983, 0.34025204, 0.34692705]], dtype=float32))

In [9]:
from flax import nnx

Rngs: nnx.Rngs = nnx.Rngs(0)

Rngs.normal((3,4))

Array([[ 1.0040143 , -0.9063372 , -0.7481722 , -1.1713669 ],
       [-0.8712328 ,  0.58883816,  0.72392994, -1.0255982 ],
       [ 1.661628  , -1.8910251 , -1.2889339 ,  0.13360691]],      dtype=float32)

### Randomly create tensors using the normal distribution (Gaussian):

In [10]:
torch.randn(3,4), Rngs.normal((3,4))

(tensor([[ 0.8162, -0.3741, -1.4221,  0.1488],
         [-0.7303, -0.8008,  1.3212, -1.1640],
         [ 0.6951,  0.0801, -1.1274, -1.6978]]),
 Array([[-2.4424558 , -2.0356805 ,  0.20554423, -0.3535502 ],
        [-0.76197404, -1.1785518 , -1.1482196 ,  0.29716578],
        [-1.3105359 ,  2.1302025 , -0.18957235,  0.9640122 ]],      dtype=float32))

### Create a tensor from a given ndarray (in Python)

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]), jnp.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

(tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]),
 Array([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=int32))

### Standard arithmetic operators (+, -, *, /, and **) can all be listed to element-wise operations for tensors.

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

xj = jnp.array([1.0, 2, 4, 8])
yj = jnp.array([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x**y, torch.exp(x), xj + yj, xj - yj, xj * yj, xj / yj, xj**yj, jnp.exp(xj)

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]),
 Array([ 3.,  4.,  6., 10.], dtype=float32),
 Array([-1.,  0.,  2.,  6.], dtype=float32),
 Array([ 2.,  4.,  8., 16.], dtype=float32),
 Array([0.5, 1. , 2. , 4. ], dtype=float32),
 Array([ 1.,  4., 16., 64.], dtype=float32),
 Array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],      dtype=float32))

### Concatenating tensors

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0), "\n", torch.cat((X, Y), dim=1))

XJ = jnp.array(X)
YJ = jnp.array(Y)

print(jnp.concat((XJ, YJ), axis=0), "\n", jnp.concat((XJ, YJ), axis=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]) 
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]] 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]


### Creating binary tensors using logical operators

In [17]:
X == Y, XJ == YJ

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 Array([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]], dtype=bool))

In [18]:
X > Y, XJ > YJ

(tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 Array([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]], dtype=bool))

In [19]:
X < Y, XJ < YJ

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 Array([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]], dtype=bool))

### Summing all elements of a tensor produces a tensor with only one element.

In [20]:
X.sum(), XJ.sum()

(tensor(66.), Array(66., dtype=float32))

### Broadcasting Mechanism: Performing tensor operations for incompatible sizes of tensors

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

aj = jnp.array(a)
bj = jnp.array(b)

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

For different shapes, the shape values with 1 get copied.
For different sizes, we right align then add 1:
- adding (2, ) to (3, 1)
- Right align: (   2), (3, 1)
- Fill empty spots with 1: (1, 2), (3, 1)
- Applying copying rule

In [22]:
a+b, aj + bj

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 Array([[0, 1],
        [1, 2],
        [2, 3]], dtype=int32))

### Access specifc elements

In [23]:
X[-1],X[1:3], X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [25]:
X[1:3, :]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### To assign the same value to multiple elements, we simply need to index all the elements and then assign the value to them.

In [26]:
X[1:3, :] = 15
print(X)
XJ = XJ.at[1:3, :].set(15)
print(XJ)

tensor([[ 0.,  1.,  2.,  3.],
        [15., 15., 15., 15.],
        [15., 15., 15., 15.]])
[[ 0.  1.  2.  3.]
 [15. 15. 15. 15.]
 [15. 15. 15. 15.]]


### Convert tensor to ndarray

In [27]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

### Convert a tensor of size 1 to a Python scalar.

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)